kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  ### Create a name for your PVC ###
  name: esa-pvc
  ### Use a namespace that matched your intended consuming pod, or "default" ###
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: cloud-backed-sc
---
apiVersion: "arccontainerstorage.azure.net/v1"
kind: EdgeSubvolume
metadata:
  name: demo-data
spec:
  edgevolume: esa-pvc
  path: demo-data # If you change this path, line 33 in deploymentExample.yaml must be updated. Don't use a preceding slash.
  auth:
    authType: MANAGED_IDENTITY
  storageaccountendpoint: "https://arcjumpstartfddemone001.blob.core.windows.net/"
  container: fault-detection
  ingestPolicy: edgeingestpolicy-demo # Optional: See the following instructions if you want to update the ingestPolicy with your own configuration
---
apiVersion: arccontainerstorage.azure.net/v1
kind: EdgeIngestPolicy
metadata:
  name: edgeingestpolicy-demo # This must be updated and referenced in the spec::ingestPolicy section of the edgeSubvolume.yaml
spec:
  ingest:
    order: oldest-first
    minDelaySec: 60
  eviction:
    order: unordered
    minDelaySec: 300
---


